### ISSUE TITLE
Navbar info drop-down

### ISSUE THREAD

**Issue by DrSqua** [IngeniumUA/ingeniumuahubfront#42]
We zijn echt véél info pagina's aant aanmaken die ni allemaal makkelijk bereikbaar zijn.

Desktop:
Dropdown toevoegen aan de navbar bovenaan? Ik denk aan een dropdown die naar beneden opent wanneer je hovert over de info component.

Mobile:
Gaan we nog ff negeren tot binnen een paar weken. Ik ga een kleine redesign van de mobile-navbar ontwerpen

**Comment by DrSqua** [comment]
@sigfriedseldeslachts Kan jij hier eens naar kijken voor me?

**Comment by sigfriedseldeslachts** [comment]
Is opgelost in https://github.com/IngeniumUA/ingeniumuahubfront/commit/6f0d13a3c11dd76aba5547f4f04de3a9c599dc6d en wordt mee gepushed in #74
